
{% set data = load_setup_py_data() %}


package:
  name: epicsmacrolib

  version: {{ data.get('version') }}


source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  build:
    - python >=3.7
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - epicsmacrolib
  requires:
    - pytest

about:
  home: https://github.com/pcdshub/epicsmacrolib
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  summary: epics-base compliant macro tools
