{% set package_name = "epicsmacrolib" %}
{% set import_name = "epicsmacrolib" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv



requirements:
  build:
  - python >=3.9,<3.10
  - setuptools_scm
  - pip
  host:
  - python >=3.9,<3.10
  - pip
  run:
  - python >=3.9,<3.10



test:
  imports:
  - epicsmacrolib
  - _epicsmacrolib
  requires:
  - pytest



about:
  home: https://github.com/pcdshub/epicsmacrolib
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  summary: epics-base compliant macro tools
